### ISSUE TITLE
Fix iOS permissions

### ISSUE THREAD

**Issue by gadkadosh** [ericberman/MyFlightbookiOS#140] opened 2019-03-24 07:16 UTC
I can add photos even though Photos permission is set to never (at least in aircraft). It should probably be changed to “add photos only”. 
Camera also opens, albeit to a black screen, even though not permitted - should probably rather give an alert. 
This is on an iPhone 6, iOS 12.1.4

Thanks for this amazing project! I would love to help but have zero dev experience with iOS...!

**Comment by ericberman** [comment] 2019-03-24 17:52
Interesting, yeah, I can reproduce that.  But the odd thing is that the os should be preventing it if permissions are not granted!

**Comment by gadkadosh** [comment] 2019-03-24 18:19
Yes, you’re right, I was really surprised. Since I don’t know anything about how iOS dev works, I figured I would just post it here, but it does feel like an iOS bug. Isn’t the App Store process supposed to catch things like that already?

**Comment by ericberman** [comment] 2019-03-24 18:30
Nah, they’re looking for if you’re using hidden APIs and stuff like that.  The system is supposed to be enforcing this.  I.e., if you fail to ask for permission, then you don’t have permission and are denied, so the overall functionality should be failing.

BTW – I think the camera with the black screen when you don’t give permission is fine.  But you shouldn’t be able to attach a picture without permission; that should simply fail.  So I think it is in fact an iOS bug, but I’ll have to explore.

--Eric

**Comment by ericberman** [comment] 2019-04-04 17:21
Finally got around to looking at this.  Looks like using UIImagePicker causes the permission request, but it is not necessary to have those permissions to access local photos.  (I guess because I declared use of photos permissions?)  So I'm leaning towards "won't fix" on this.  If you deny permissions, the "right" thing is for iOS to simply never send me a selected image.

**Closed by ericberman** 2019-04-04 17:21 UTC
