### ISSUE TITLE
Bug: After unchecking templates while adding a new flight, the checkmarks reappear and unwanted properties remain checked

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookiOS#259] opened 2021-11-16 06:57 UTC
The properties also reflect the pre-change selections

**Comment by zartom** [comment] 2021-11-16 07:28
This issue should be copied to the Web repository, as the issue appears there as well

**Comment by ericberman** [comment] 2021-11-16 22:54
I can't reproduce this.  Can you give specific steps?
Note that the following do not go away even if you uncheck them (by design):
 - Templates based on the aircraft
 - Sim template if you've selected a sim
 - Anonymous template if you've selected an anonymous aircraft.

So, for example, the only way I can reproduce this is if I use one my club aircraft, which has a "club VFR Flight" template associated with it.  While that plane is selected, the club VFR Flight template is active.  This is by design - it would create all sorts of bizarre user interface behavior if that were not the case.

Is that possibly what's happening?

**Comment by ericberman** [comment] 2021-11-19 17:40
I'm looking at your templates in your account right now.  You have both CAL and SkyDiving Pilot - the ones that don't go away - marked as being default.  So the behavior is expected.

**Closed by ericberman** 2021-11-19 17:40 UTC

**Comment by zartom** [comment] 2021-11-20 07:37
Awesome, thanks!
